services:
  spark:
    version: 3.1.2
  hdfs:
    version: 3.2.0

provider: ec2

providers:
  ec2:
    key-name: clo-spark-key
    identity-file: /Users/zhewang/Projects/CLO/clo-spark-key.pem
    instance-type: m5.large
    region: eu-west-2
    ami: ami-0d26eb3972b7f8c96  # Amazon Linux 2, us-east-1
    user: ec2-user
    instance-profile-name: s3-admin
    user-data: "/Users/zhewang/Projects/CLO/user_data.txt"

launch:
  num-slaves: 1
  install-hdfs: False  # this is needed for S3 access
